# Generated by Django 3.1.6 on 2021-06-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210602_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
