# Generated by Django 3.1.6 on 2021-06-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(default='60%', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.IntegerField(default=10, max_length=5000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tag_line',
            field=models.TextField(default='Add Your Tagline Here'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='skill', to='accounts.Skills'),
        ),
    ]
