# Generated by Django 3.1.6 on 2021-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210602_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.CharField(default='Enter Service Hourly Rate ($)', max_length=20),
        ),
    ]
