# Generated by Django 3.1.6 on 2021-06-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210602_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
