# Generated by Django 3.1.6 on 2021-06-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_skills_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='rating',
        ),
    ]
