# Generated by Django 3.1.6 on 2021-06-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_skills_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.CharField(default='Enter Service Hourly Rate ($)', max_length=200),
        ),
    ]
