# Generated by Django 3.1.6 on 2021-06-02 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20210602_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=200)),
                ('starting_date', models.CharField(default='', max_length=200)),
                ('ending_date', models.CharField(blank=True, default='Present', max_length=200, null=True)),
                ('job_title', models.CharField(default='', max_length=200)),
                ('job_description', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
