# Generated by Django 3.1.6 on 2021-06-02 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=200)),
                ('starting_date', models.CharField(default='', max_length=200)),
                ('ending_date', models.CharField(blank=True, default='Present', max_length=200, null=True)),
                ('degree', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
