# Generated by Django 3.1.6 on 2021-06-03 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='proposal_count',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('bid', models.CharField(max_length=1000)),
                ('duration', models.CharField(default='', max_length=200)),
                ('timeCreated', models.DateField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalsender', to=settings.AUTH_USER_MODEL)),
                ('on_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobproposal', to='accounts.job')),
            ],
        ),
    ]
