# Generated by Django 3.1.6 on 2021-06-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210604_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='budget',
            field=models.CharField(default='', max_length=300),
        ),
    ]
