# Generated by Django 3.1.6 on 2021-06-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_job_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pending_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
