# Generated by Django 3.1.6 on 2021-06-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210605_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
