# Generated by Django 3.1.6 on 2021-06-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210605_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pending_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
