# Generated by Django 3.1.6 on 2021-06-05 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_job_pending_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='on_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_job', to='accounts.job'),
        ),
    ]
